# Generated by Django 5.2.7 on 2025-11-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_session_id_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_pay',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
