# Generated by Django 5.2.7 on 2025-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_date_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
