# Generated by Django 5.2.7 on 2025-11-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
